name: iotx
version: "0.0.1"
summary: x project for iot on raspberry pi
description: iotivity on raspberry pi

grade: devel
confinement: devmode
apps:
  x-assistant:
    command: x-assistant

parts:
  x-assistant:
    plugin: autotools
    source: x-assistant/
    after: [bcm2835]
  bcm2835:
    plugin: autotools
    source: http://www.airspayce.com/mikem/bcm2835/bcm2835-1.52.tar.gz